name: willshex_triangles_workspace
environment:
  sdk: ">=3.5.0 <4.0.0"

workspace:
  - packages/client_cli
  - packages/client_common
  - packages/client_flutter
  - packages/client_web
  - packages/subtle_backgrounds
  - packages/willshex_draw

dependencies:
  logging: ^1.2.0
  path: ^1.9.0
  willshex:
    path: ../willshex-dart

dependency_overrides:
  build: ^4.0.0
  dart_style: 3.1.8
  analyzer: ^12.1.0
  cli_util: ^0.5.0
