name: subtle_backgrounds
description: A collection of subtle background patterns.
version: 0.0.1
publish_to: "none"
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

flutter:
  assets:
    - assets/images/
