include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "build/**"
    - ".dart_tool/**"
    - "**/*.g.dart"
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    prefer_single_quotes: false
    prefer_double_quotes: true
    curly_braces_in_flow_control_structures: true
